CREATE TABLE `customer_cd` (
    `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(50) NOT NULL,
    `middle_name` VARCHAR(50) NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `date_of_birth` DATE NOT NULL,
    `email_id` VARCHAR(50) NOT NULL,
    `phone_number` VARCHAR(50) NOT NULL,
    `gender` VARCHAR(6) NOT NULL,
    `house_no` VARCHAR(50) NOT NULL,
    `street_address` VARCHAR(50) NOT NULL,
    `street_address2` VARCHAR(50) NULL,
    `city` VARCHAR(50) NOT NULL,
    `post_code` VARCHAR(50) NOT NULL,
    `country` VARCHAR(50) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `logged_in` TINYINT(1) NOT NULL DEFAULT '0',
    `last_activity` DATETIME NOT NULL,
    `otp_generated` VARCHAR(6) NOT NULL,
    `otp_generated_at` DATETIME NOT NULL,
    `is_otp_verified` TINYINT(1) NOT NULL,
    PRIMARY KEY (`customer_id`),
    INDEX `customer_cd_first_name_index` (`first_name`),
    INDEX `customer_cd_last_name_index` (`last_name`)
);
